# -*- coding: utf-8 -*-
"""DeepLab Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/tensorflow/models/blob/master/research/deeplab/deeplab_demo.ipynb#scrollTo=c4oXKmnjw6i_

# Overview

This colab demonstrates the steps to use the DeepLab model to perform semantic segmentation on a sample input image. Expected outputs are semantic labels overlayed on the sample image.

### About DeepLab
The models used in this colab perform semantic segmentation. Semantic segmentation models focus on assigning semantic labels, such as sky, person, or car, to multiple objects and stuff in a single image.

# Instructions
<h3><a href="https://cloud.google.com/tpu/"><img valign="middle" src="https://raw.githubusercontent.com/GoogleCloudPlatform/tensorflow-without-a-phd/master/tensorflow-rl-pong/images/tpu-hexagon.png" width="50"></a>  &nbsp;&nbsp;Use a free TPU device</h3>

   1. On the main menu, click Runtime and select **Change runtime type**. Set "TPU" as the hardware accelerator.
   1. Click Runtime again and select **Runtime > Run All**. You can also run the cells manually with Shift-ENTER.

## Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import argparse
from io import BytesIO
import tarfile
import tempfile
from six.moves import urllib

from matplotlib import gridspec
from matplotlib import pyplot as plt
import numpy as np
from PIL import Image

# %tensorflow_version 1.x
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

"""## Import helper methods
These methods help us perform the following tasks:
* Load the latest version of the pretrained DeepLab model
* Load the colormap from the PASCAL VOC dataset
* Adds colors to various labels, such as "pink" for people, "green" for bicycle and more
* Visualize an image, and add an overlay of colors on various regions
"""

class DeepLabModel(object):
  """Class to load deeplab model and run inference."""

  INPUT_TENSOR_NAME = 'ImageTensor:0'
  OUTPUT_TENSOR_NAME = 'SemanticPredictions:0'
  INPUT_SIZE = 513
  FROZEN_GRAPH_NAME = 'frozen_inference_graph'

  def __init__(self, tarball_path):
    """Creates and loads pretrained deeplab model."""
    self.graph = tf.Graph()

    graph_def = None
    # Extract frozen graph from tar archive.
    tar_file = tarfile.open(tarball_path)
    for tar_info in tar_file.getmembers():
      if self.FROZEN_GRAPH_NAME in os.path.basename(tar_info.name):
        file_handle = tar_file.extractfile(tar_info)
        graph_def = tf.GraphDef.FromString(file_handle.read())
        break

    tar_file.close()

    if graph_def is None:
      raise RuntimeError('Cannot find inference graph in tar archive.')

    with self.graph.as_default():
      tf.import_graph_def(graph_def, name='')

    self.sess = tf.Session(graph=self.graph)

  def run(self, image):
    """Runs inference on a single image.

    Args:
      image: A PIL.Image object, raw input image.

    Returns:
      resized_image: RGB image resized from original input image.
      seg_map: Segmentation map of `resized_image`.
    """
    width, height = image.size
    resize_ratio = 1.0 * self.INPUT_SIZE / max(width, height)
    target_size = (int(resize_ratio * width), int(resize_ratio * height))
    # Use Image.Resampling.LANCZOS for modern Pillow compatibility (Pillow >= 10)
    resized_image = image.convert('RGB').resize(target_size, Image.Resampling.LANCZOS)
    batch_seg_map = self.sess.run(
        self.OUTPUT_TENSOR_NAME,
        feed_dict={self.INPUT_TENSOR_NAME: [np.asarray(resized_image)]})
    seg_map = batch_seg_map[0]
    return resized_image, seg_map


def create_pascal_label_colormap():
  """Creates a label colormap used in PASCAL VOC segmentation benchmark.

  Returns:
    A Colormap for visualizing segmentation results.
  """
  colormap = np.zeros((256, 3), dtype=int)
  ind = np.arange(256, dtype=int)

  for shift in reversed(range(8)):
    for channel in range(3):
      colormap[:, channel] |= ((ind >> channel) & 1) << shift
    ind >>= 3

  return colormap


def label_to_color_image(label):
  """Adds color defined by the dataset colormap to the label.

  Args:
    label: A 2D array with integer type, storing the segmentation label.

  Returns:
    result: A 2D array with floating type. The element of the array
      is the color indexed by the corresponding element in the input label
      to the PASCAL color map.

  Raises:
    ValueError: If label is not of rank 2 or its value is larger than color
      map maximum entry.
  """
  if label.ndim != 2:
    raise ValueError('Expect 2-D input label')

  colormap = create_pascal_label_colormap()

  if np.max(label) >= len(colormap):
    raise ValueError('label value too large.')

  return colormap[label]


def vis_segmentation(image, seg_map, save_path=None):
  """Visualizes input image, segmentation map and overlay view."""
  plt.figure(figsize=(15, 5))
  grid_spec = gridspec.GridSpec(1, 4, width_ratios=[6, 6, 6, 1])

  plt.subplot(grid_spec[0])
  plt.imshow(image)
  plt.axis('off')
  plt.title('input image')

  plt.subplot(grid_spec[1])
  seg_image = label_to_color_image(seg_map).astype(np.uint8)
  plt.imshow(seg_image)
  plt.axis('off')
  plt.title('segmentation map')

  plt.subplot(grid_spec[2])
  plt.imshow(image)
  plt.imshow(seg_image, alpha=0.7)
  plt.axis('off')
  plt.title('segmentation overlay')

  unique_labels = np.unique(seg_map)
  ax = plt.subplot(grid_spec[3])
  plt.imshow(
      FULL_COLOR_MAP[unique_labels].astype(np.uint8), interpolation='nearest')
  ax.yaxis.tick_right()
  plt.yticks(range(len(unique_labels)), LABEL_NAMES[unique_labels])
  plt.xticks([], [])
  ax.tick_params(width=0.0)
  plt.grid('off')

  if save_path:
    plt.savefig(save_path, bbox_inches='tight', dpi=150)
    print(f'Result saved to: {save_path}')

  plt.show()


LABEL_NAMES = np.asarray([
    'background', 'aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus',
    'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike',
    'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tv'
])

FULL_LABEL_MAP = np.arange(len(LABEL_NAMES)).reshape(len(LABEL_NAMES), 1)
FULL_COLOR_MAP = label_to_color_image(FULL_LABEL_MAP)

"""## Select a pretrained model
We have trained the DeepLab model using various backbone networks. Select one from the MODEL_NAME list.
"""

MODEL_NAME = 'mobilenetv2_coco_voctrainaug'  # @param ['mobilenetv2_coco_voctrainaug', 'mobilenetv2_coco_voctrainval', 'xception_coco_voctrainaug', 'xception_coco_voctrainval']

_DOWNLOAD_URL_PREFIX = 'http://download.tensorflow.org/models/'
_MODEL_URLS = {
    'mobilenetv2_coco_voctrainaug':
        'deeplabv3_mnv2_pascal_train_aug_2018_01_29.tar.gz',
    'mobilenetv2_coco_voctrainval':
        'deeplabv3_mnv2_pascal_trainval_2018_01_29.tar.gz',
    'xception_coco_voctrainaug':
        'deeplabv3_pascal_train_aug_2018_01_04.tar.gz',
    'xception_coco_voctrainval':
        'deeplabv3_pascal_trainval_2018_01_04.tar.gz',
}
_TARBALL_NAME = 'deeplab_model.tar.gz'

# Caching model download locally in a './models' directory
model_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'models')
os.makedirs(model_dir, exist_ok=True)

_SAMPLE_URL = ('https://github.com/tensorflow/models/blob/master/research/'
               'deeplab/g3doc/img/%s.jpg?raw=true')

def run_visualization(MODEL, image_path_or_url):
  """Inferences DeepLab model and visualizes result."""
  try:
    if image_path_or_url.startswith('http://') or image_path_or_url.startswith('https://'):
      print('Downloading image from URL: ' + image_path_or_url)
      f = urllib.request.urlopen(image_path_or_url)
      jpeg_str = f.read()
      original_im = Image.open(BytesIO(jpeg_str))
    else:
      print('Loading local image: ' + image_path_or_url)
      original_im = Image.open(image_path_or_url)
  except IOError as e:
    print('Cannot retrieve/load image. Please check path/url: ' + image_path_or_url)
    print('Error details:', e)
    return

  print('Running DeepLab inference...')
  resized_im, seg_map = MODEL.run(original_im)

  # Determine result filename
  if image_path_or_url.startswith('http://') or image_path_or_url.startswith('https://'):
    base_name = image_path_or_url.split('/')[-1].split('?')[0]
  else:
    base_name = os.path.basename(image_path_or_url)

  name_without_ext, _ = os.path.splitext(base_name)
  if not name_without_ext:
    name_without_ext = 'result'

  # Create 'resultados' directory relative to script
  output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'resultados')
  os.makedirs(output_dir, exist_ok=True)
  save_path = os.path.join(output_dir, f'{name_without_ext}_segmentation.png')

  vis_segmentation(resized_im, seg_map, save_path=save_path)

def main():
  parser = argparse.ArgumentParser(description='DeepLab Semantic Segmentation Demo (Local Version)')
  parser.add_argument('--model', type=str, default='mobilenetv2_coco_voctrainaug',
                      choices=list(_MODEL_URLS.keys()),
                      help='DeepLab model name')
  parser.add_argument('--image', type=str, nargs='*', default=[],
                      help='Path to local image(s) or image URL(s) (supports multiple separated by spaces or commas)')
  parser.add_argument('--sample', type=str, nargs='*', default=['image1', 'image2', 'image3'],
                      help='Sample image name(s) to use if --image is not provided')
  args = parser.parse_args()

  # Set up download path for selected model
  tarball_name = _MODEL_URLS[args.model]
  download_path = os.path.join(model_dir, tarball_name)

  if not os.path.exists(download_path):
    print(f'Downloading model {args.model}, this might take a while...')
    model_url = _DOWNLOAD_URL_PREFIX + tarball_name
    urllib.request.urlretrieve(model_url, download_path)
    print('Download completed!')
  else:
    print(f'Model {args.model} found locally in cache, skipping download.')

  print('Loading DeepLab model...')
  model = DeepLabModel(download_path)
  print('Model loaded successfully!')

  # Build a list of image paths/URLs to process
  images_to_process = []
  
  # Normalize args.image to a list
  images_input = args.image
  if isinstance(images_input, str):
    images_input = [images_input] if images_input else []
  
  if images_input:
    for img in images_input:
      if ',' in img:
        images_to_process.extend([i.strip() for i in img.split(',') if i.strip()])
      else:
        images_to_process.append(img)
  else:
    # Normalize args.sample to a list
    samples_input = args.sample
    if isinstance(samples_input, str):
      samples_input = [samples_input]
    
    actual_samples = []
    for s in samples_input:
      if ',' in s:
        actual_samples.extend([si.strip() for si in s.split(',') if si.strip()])
      else:
        actual_samples.append(s)
        
    for sample in actual_samples:
      images_to_process.append(_SAMPLE_URL % sample)

  print(f'Found {len(images_to_process)} image(s) to process.')
  for i, img_path_or_url in enumerate(images_to_process, 1):
    print(f'\n--- Processing image {i}/{len(images_to_process)}: {img_path_or_url} ---')
    run_visualization(model, img_path_or_url)

if __name__ == '__main__':
  main()

"""## What's next

* Learn about [Cloud TPUs](https://cloud.google.com/tpu/docs) that Google designed and optimized specifically to speed up and scale up ML workloads for training and inference and to enable ML engineers and researchers to iterate more quickly.
* Explore the range of [Cloud TPU tutorials and Colabs](https://cloud.google.com/tpu/docs/tutorials) to find other examples that can be used when implementing your ML project.
* For more information on running the DeepLab model on Cloud TPUs, see the [DeepLab tutorial](https://cloud.google.com/tpu/docs/tutorials/deeplab).

"""