# -*- coding: utf-8 -*-
"""Confusion Matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWLRjDZ_SsDF8FeE42eYq4pXfQnfpSMI
"""

# !pip install -q tensorflow

import io
import shutil
import os
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import seaborn as sns
import pandas as pd

import tensorflow as tf
print(tf.__version__)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

logdir = 'log'
os.makedirs(logdir, exist_ok=True)
if os.name == 'nt':
    import ctypes
    buf_size = 256
    buffer = ctypes.create_unicode_buffer(buf_size)
    ctypes.windll.kernel32.GetShortPathNameW(
        os.path.abspath(logdir), buffer, buf_size)
    logdir = buffer.value

shutil.rmtree(logdir, ignore_errors=True)
os.makedirs(logdir, exist_ok=True)

os.makedirs('resultados', exist_ok=True)

(train_images, train_labels), (test_images,
                               test_labels) = datasets.mnist.load_data()

train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))

train_images, test_images = train_images / 255.0, test_images / 255.0

classes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(x=train_images,
                    y=train_labels,
                    epochs=5,
                    validation_data=(test_images, test_labels))

y_true = test_labels
y_pred_probabilities = model.predict(test_images)
y_pred = np.argmax(y_pred_probabilities, axis=1)

classes = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

con_mat = tf.math.confusion_matrix(labels=y_true, predictions=y_pred).numpy()
con_mat_norm = np.around(con_mat.astype('float') /
                         con_mat.sum(axis=1)[:, np.newaxis], decimals=2)

con_mat_df = pd.DataFrame(con_mat_norm,
                          index=classes,
                          columns=classes)

figure = plt.figure(figsize=(8, 8))
sns.heatmap(con_mat_df, annot=True, cmap=plt.cm.Blues)
plt.tight_layout()
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.savefig('resultados/confusion_matrix_model1.png')
plt.close(figure)

# Write Model 1 results to a file
with open('resultados/resultados.txt', 'w', encoding='utf-8') as f:
    f.write("=== METRICAS E RESULTADOS DE AVALIACAO ===\n\n")
    f.write(f"TensorFlow Version: {tf.__version__}\n\n")

    f.write("=== MODELO 1: SUMARIO ===\n")
    model.summary(print_fn=lambda x: f.write(x + '\n'))
    f.write("\n")

    f.write("=== MODELO 1: HISTORICO DE TREINAMENTO ===\n")
    for epoch in range(len(history.history['accuracy'])):
        f.write(f"Epoch {epoch+1}/5:\n")
        f.write(
            f"  Loss: {history.history['loss'][epoch]:.4f} - Accuracy: {history.history['accuracy'][epoch]:.4f}")
        f.write(
            f" - Val Loss: {history.history['val_loss'][epoch]:.4f} - Val Accuracy: {history.history['val_accuracy'][epoch]:.4f}\n")
    f.write("\n")

    f.write("=== MODELO 1: MATRIZ DE CONFUSAO (NORMALIZADA) ===\n")
    f.write(con_mat_df.to_string())
    f.write("\n\n")

model1 = models.Sequential()
model1.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model1.add(layers.MaxPooling2D((2, 2)))
model1.add(layers.Conv2D(64, (3, 3), activation='relu'))
model1.add(layers.MaxPooling2D((2, 2)))
model1.add(layers.Conv2D(64, (3, 3), activation='relu'))

model1.add(layers.Flatten())
model1.add(layers.Dense(64, activation='relu'))
model1.add(layers.Dense(10, activation='softmax'))

model1.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)


file_writer = tf.summary.create_file_writer(os.path.join(logdir, 'cm'))


def log_confusion_matrix(epoch, logs):
    # Use the model to predict the values from the validation dataset.
    test_pred_probabilities = model1.predict(test_images)
    test_pred = np.argmax(test_pred_probabilities, axis=1)

    con_mat = tf.math.confusion_matrix(
        labels=test_labels, predictions=test_pred).numpy()
    con_mat_norm = np.around(con_mat.astype(
        'float') / con_mat.sum(axis=1)[:, np.newaxis], decimals=2)

    con_mat_df = pd.DataFrame(con_mat_norm,
                              index=classes,
                              columns=classes)

    figure = plt.figure(figsize=(8, 8))
    sns.heatmap(con_mat_df, annot=True, cmap=plt.cm.Blues)
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

    # Save image to resultados folder
    plt.savefig(f'resultados/confusion_matrix_model2_epoch_{epoch+1}.png')

    buf = io.BytesIO()
    plt.savefig(buf, format='png')

    plt.close(figure)
    buf.seek(0)
    image = tf.image.decode_png(buf.getvalue(), channels=4)
    image = tf.expand_dims(image, 0)

    # Log the confusion matrix as an image summary.
    with file_writer.as_default():
        tf.summary.image("Confusion Matrix", image, step=epoch)


tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)
cm_callback = tf.keras.callbacks.LambdaCallback(
    on_epoch_end=log_confusion_matrix)

history1 = model1.fit(
    train_images,
    train_labels,
    epochs=5,
    verbose=0,
    callbacks=[tensorboard_callback, cm_callback],
    validation_data=(test_images, test_labels),
)

# Write Model 2 results to the file
with open('resultados/resultados.txt', 'a', encoding='utf-8') as f:
    f.write("=== MODELO 2: SUMARIO ===\n")
    model1.summary(print_fn=lambda x: f.write(x + '\n'))
    f.write("\n")

    f.write("=== MODELO 2: HISTORICO DE TREINAMENTO ===\n")
    for epoch in range(len(history1.history['accuracy'])):
        f.write(f"Epoch {epoch+1}/5:\n")
        f.write(
            f"  Loss: {history1.history['loss'][epoch]:.4f} - Accuracy: {history1.history['accuracy'][epoch]:.4f}")
        f.write(
            f" - Val Loss: {history1.history['val_loss'][epoch]:.4f} - Val Accuracy: {history1.history['val_accuracy'][epoch]:.4f}\n")
    f.write("\n")

    # Save final model 2 confusion matrix to file
    test_pred_probabilities = model1.predict(test_images)
    test_pred = np.argmax(test_pred_probabilities, axis=1)
    con_mat = tf.math.confusion_matrix(
        labels=test_labels, predictions=test_pred).numpy()
    con_mat_norm = np.around(con_mat.astype(
        'float') / con_mat.sum(axis=1)[:, np.newaxis], decimals=2)
    con_mat_df = pd.DataFrame(con_mat_norm, index=classes, columns=classes)

    f.write("=== MODELO 2: MATRIZ DE CONFUSAO FINAL (NORMALIZADA) ===\n")
    f.write(con_mat_df.to_string())
    f.write("\n")

# Commented out IPython magic to ensure Python compatibility.
# Start TensorBoard.
# %tensorboard --logdir log
