# -*- coding: utf-8 -*-
"""hsv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/YoniChechik/AI_is_Math/blob/master/c_02a_basic_image_processing/hsv.ipynb

# HSV color space
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/YoniChechik/AI_is_Math/blob/master/c_02a_basic_image_processing/hsv.ipynb)
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import os
import urllib.request

def baixar_imagem(url, pasta_destino, nome_arquivo):
    """
    Cria a pasta de destino caso não exista e realiza o download da imagem a partir da URL.
    """
    os.makedirs(pasta_destino, exist_ok=True)
    caminho_completo = os.path.join(pasta_destino, nome_arquivo)

    if not os.path.exists(caminho_completo):
        print(f"Baixando imagem de: {url}...")
        try:
            # Usar um cabeçalho User-Agent para evitar problemas de requisição bloqueada
            req = urllib.request.Request(
                url,
                headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
            )
            with urllib.request.urlopen(req) as response:
                with open(caminho_completo, 'wb') as f:
                    f.write(response.read())
            print(f"Imagem baixada e salva com sucesso em: '{caminho_completo}'")
        except Exception as e:
            print(f"Erro ao baixar a imagem: {e}")
            return None
    else:
        print(f"Imagem já existente em: '{caminho_completo}'")

    return caminho_completo

def main():
    # URL da imagem do gramado
    url_grass = "https://github.com/YoniChechik/AI_is_Math/raw/master/c_02a_basic_image_processing/grass.jpg"
    pasta_imagens = "imagens"
    pasta_resultado = "resultado"
    nome_arquivo = "grass.jpg"

    # Baixar a imagem
    caminho_imagem = baixar_imagem(url_grass, pasta_imagens, nome_arquivo)

    if caminho_imagem and os.path.exists(caminho_imagem):
        # Adopted from: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_colorspaces/py_colorspaces.html
        figsize = (10, 10)

        # Criar a pasta de resultados
        os.makedirs(pasta_resultado, exist_ok=True)

        # Ler imagem básica
        bgr_im = cv2.imread(caminho_imagem)
        if bgr_im is None:
            print("Erro ao carregar a imagem com OpenCV.")
            return

        rgb_im = cv2.cvtColor(bgr_im, cv2.COLOR_BGR2RGB)

        # Mostrar imagem original
        plt.figure(figsize=figsize)
        plt.imshow(rgb_im)
        plt.title("Original Image")
        
        # Salvar imagem original no resultado
        caminho_original = os.path.join(pasta_resultado, "original.png")
        plt.savefig(caminho_original, bbox_inches='tight')
        print(f"Imagem original salva em: '{caminho_original}'")
        
        try:
            plt.show()
        except Exception as e:
            print(f"Não foi possível exibir a janela do Matplotlib: {e}")

        """We want to separate the grass from the sky. we'll do this by masking all pixels in the image that are not green.

        First, find HSV green
        """
        rgb_green = np.uint8([[[0, 255, 0]]])  # 3d array just because this is what cvtColor expects...
        hsv_green = cv2.cvtColor(rgb_green, cv2.COLOR_RGB2HSV)[0, 0, :]
        print(f"HSV Green: {hsv_green}")

        """Second, convert the image to HSV and threshold only the green color and neighborhood.

        We will take hue TH of +30 and -70 (because it's farther from blue- the sky).
        Let's take all saturation and value variants of green in the TH.

        Masking all that is in the TH should give us only the grass
        """

        # Convert BGR to HSV
        hsv_im = cv2.cvtColor(rgb_im, cv2.COLOR_RGB2HSV)

        # define range of hue and intensity
        lower_th = hsv_green - np.array([70, 200, 200])
        upper_th = hsv_green + np.array([30, 0, 0])

        # Threshold the HSV image
        mask = cv2.inRange(hsv_im, lower_th, upper_th)

        plt.figure(figsize=figsize)
        plt.imshow(mask, cmap='gray')
        plt.title("Resulted Mask")
        
        # Salvar máscara resultante no resultado
        caminho_mascara = os.path.join(pasta_resultado, "mascara.png")
        plt.savefig(caminho_mascara, bbox_inches='tight')
        print(f"Máscara resultante salva em: '{caminho_mascara}'")
        
        try:
            plt.show()
        except Exception as e:
            print(f"Não foi possível exibir a janela do Matplotlib: {e}")

        # Trick: apply 2d mask on 3d image
        rgb_res = cv2.bitwise_and(rgb_im, rgb_im, mask=mask)

        plt.figure(figsize=figsize)
        plt.imshow(rgb_res)
        plt.title("Output Image")
        
        # Salvar resultado final no resultado
        caminho_resultado = os.path.join(pasta_resultado, "resultado_final.png")
        plt.savefig(caminho_resultado, bbox_inches='tight')
        print(f"Imagem resultante salva em: '{caminho_resultado}'")
        
        try:
            plt.show()
        except Exception as e:
            print(f"Não foi possível exibir a janela do Matplotlib: {e}")
            
        # Também salvar o resultado direto sem matplotlib (usando cv2)
        bgr_res = cv2.cvtColor(rgb_res, cv2.COLOR_RGB2BGR)
        caminho_res_direto = os.path.join(pasta_resultado, "resultado_direto.png")
        cv2.imwrite(caminho_res_direto, bgr_res)
        print(f"Imagem final direta salva usando OpenCV em: '{caminho_res_direto}'")

    else:
        print("Erro: Não foi possível obter ou carregar a imagem 'grass.jpg'.")

if __name__ == "__main__":
    main()