# -*- coding: utf-8 -*-
"""2020-08-02-01-Filters-Contrast-Transformation-and-Morphology.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/goodboychan/chans_jupyter/blob/main/_notebooks/2020-08-02-01-Filters-Contrast-Transformation-and-Morphology.ipynb

# Filters, Contrast, Transformation and Morphology
> You will learn to detect object shapes using edge detection filters, improve medical images with contrast enhancement and even enlarge pictures to five times its original size! You will also apply morphology to make thresholding more accurate when segmenting images and go to the next level of processing images with Python. This is the Summary of lecture "Image Processing in Python", via datacamp.

- toc: true
- badges: true
- comments: true
- author: Chanseok Kang
- categories: [Python, Datacamp, Vision]
- image: images/edge_sobel.png
"""

import os
import urllib.request
import numpy as np
import matplotlib.pyplot as plt
from skimage import color, exposure, data, morphology
from skimage.filters import sobel, gaussian
from skimage.transform import rotate, rescale, resize

# --- Setup local paths and download directories ---
script_dir = os.path.dirname(os.path.abspath(__file__))
downloads_dir = os.path.join(script_dir, "downloads")
resultados_dir = os.path.join(script_dir, "resultados")

os.makedirs(downloads_dir, exist_ok=True)
os.makedirs(resultados_dir, exist_ok=True)

print(f"Diretório de downloads: {downloads_dir}")
print(f"Diretório de resultados: {resultados_dir}\n")

def get_image_path(filename):
    """
    Checks if the image exists in the local downloads folder.
    If not, downloads it from the source GitHub repository.
    """
    local_path = os.path.join(downloads_dir, filename)
    if not os.path.exists(local_path):
        print(f"Baixando imagem '{filename}'...")
        url = f"https://github.com/goodboychan/chans_jupyter/raw/main/_notebooks/dataset/{filename}"
        try:
            urllib.request.urlretrieve(url, local_path)
            print(f"'{filename}' baixada com sucesso.")
        except Exception as e:
            print(f"Erro ao baixar de '{url}': {e}. Tentando fallback...")
            fallback_url = f"https://raw.githubusercontent.com/goodboychan/chans_jupyter/master/_notebooks/dataset/{filename}"
            try:
                urllib.request.urlretrieve(fallback_url, local_path)
                print(f"'{filename}' baixada com sucesso (fallback).")
            except Exception as e2:
                print(f"Erro ao baixar de '{fallback_url}': {e2}")
                raise e2
    return local_path

def show_image(image, title='Image', cmap_type='gray'):
    plt.imshow(image, cmap=cmap_type)
    plt.title(title)
    plt.axis('off')

# =====================================================================
# Jump into filtering
# =====================================================================

"""### Edge detection
In this exercise, you'll detect edges in an image by applying the Sobel filter.
"""
print("--- 1. Detecção de Bordas (Sobel) ---")
soaps_image = plt.imread(get_image_path('soap_image.jpg'))

# Make the image grayscale
soaps_image_gray = color.rgb2gray(soaps_image)

# apply edge detection filters
edge_sobel = sobel(soaps_image_gray)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(soaps_image, 'Original')
plt.subplot(1, 2, 2)
show_image(edge_sobel, 'Edges with Sobel')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '1_edge_detection_sobel.png'))
plt.close()
print("Resultado salvo em 'resultados/1_edge_detection_sobel.png'\n")


"""### Blurring to reduce noise
In this exercise you will reduce the sharpness of an image of a building taken during a London trip, through filtering.
"""
print("--- 2. Suavização Gaussiana (Blur) ---")
building_image = plt.imread(get_image_path('building_image.jpg'))

# Apply filter (handling deprecation of multichannel in newer skimage versions)
try:
    gaussian_image = gaussian(building_image, multichannel=True)
except TypeError:
    gaussian_image = gaussian(building_image, channel_axis=-1)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(building_image, 'Original')
plt.subplot(1, 2, 2)
show_image(gaussian_image, 'Reduced sharpness Gaussian')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '2_gaussian_blurring.png'))
plt.close()
print("Resultado salvo em 'resultados/2_gaussian_blurring.png'\n")


# =====================================================================
# Contrast enhancement
# =====================================================================

"""### Medical images
You'll test our code on a chest X-ray image from the National Institutes of Health Chest X-Ray Dataset.
First, you'll check the histogram of the image and then apply standard histogram equalization to improve the contrast.
"""
print("--- 3. Imagem Médica (Equalização de Histograma) ---")
chest_xray_image = plt.imread(get_image_path('chest_xray_image.png'))

# Use histogram equalization to improve the contrast
xray_image_eq = exposure.equalize_hist(chest_xray_image)

# Plot and save original, histogram, and equalized result
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
show_image(chest_xray_image, 'Original x-ray')
plt.subplot(1, 3, 2)
plt.title('Histogram of original image')
plt.hist(chest_xray_image.ravel(), bins=256)
plt.subplot(1, 3, 3)
show_image(xray_image_eq, 'Equalized x-ray')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '3_chest_xray_equalized.png'))
plt.close()
print("Resultado salvo em 'resultados/3_chest_xray_equalized.png'\n")


"""### Aerial image
In this exercise, we will improve the quality of an aerial image of a city using standard Histogram Equalization.
"""
print("--- 4. Imagem Aérea (Equalização de Histograma) ---")
image_aerial = plt.imread(get_image_path('image_aerial.png'))

# Use histogram equalization to improve the contrast
image_eq = exposure.equalize_hist(image_aerial)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(image_aerial, 'Original')
plt.subplot(1, 2, 2)
show_image(image_eq, 'Resulting image')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '4_aerial_image_equalized.png'))
plt.close()
print("Resultado salvo em 'resultados/4_aerial_image_equalized.png'\n")


"""### Let's add some impact and contrast
In this exercise, you'll increase the contrast of a cup of coffee using adaptive equalization (CLAHE).
"""
print("--- 5. Copo de Café (Equalização Adaptativa - CLAHE) ---")
original_image = data.coffee()

# Apply the adaptive equalization on the original image
adapthist_eq_image = exposure.equalize_adapthist(original_image, clip_limit=0.03)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(original_image, 'Original Coffee')
plt.subplot(1, 2, 2)
show_image(adapthist_eq_image, 'Adaptive Equalized')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '5_coffee_adaptive_equalized.png'))
plt.close()
print("Resultado salvo em 'resultados/5_coffee_adaptive_equalized.png'\n")


# =====================================================================
# Transformations
# =====================================================================

"""### Aliasing, rotating and rescaling
You'll make this cat image upright by rotating it 90 degrees and then rescaling it two times (with and without anti-aliasing).
"""
print("--- 6. Rotação e Redimensionamento (Anti-Aliasing) ---")
image_cat = plt.imread(get_image_path('image_cat.jpg'))

# Rotate the image 90 degress clockwise
rotated_cat_image = rotate(image_cat, -90)

# Rescale (handling deprecation of multichannel in newer skimage versions)
try:
    rescaled_with_aa = rescale(rotated_cat_image, 1/4, anti_aliasing=True, multichannel=True)
    rescaled_without_aa = rescale(rotated_cat_image, 1/4, anti_aliasing=False, multichannel=True)
except TypeError:
    rescaled_with_aa = rescale(rotated_cat_image, 1/4, anti_aliasing=True, channel_axis=-1)
    rescaled_without_aa = rescale(rotated_cat_image, 1/4, anti_aliasing=False, channel_axis=-1)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(rescaled_with_aa, 'Transformed with anti aliasing')
plt.subplot(1, 2, 2)
show_image(rescaled_without_aa, 'Transformed without anti aliasing')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '6_cat_rescaled_comparison.png'))
plt.close()
print("Resultado salvo em 'resultados/6_cat_rescaled_comparison.png'\n")


"""### Enlarging images
In this exercise you'll enlarge a rocket image three times.
"""
print("--- 7. Ampliação de Imagem (Rocket) ---")
rocket_image = data.rocket()

# Enlarge the image so it is 3 times bigger (handling multichannel deprecation)
try:
    enlarged_rocket_image = rescale(rocket_image, 3, anti_aliasing=True, multichannel=True)
except TypeError:
    enlarged_rocket_image = rescale(rocket_image, 3, anti_aliasing=True, channel_axis=-1)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(rocket_image, 'Original Rocket')
plt.subplot(1, 2, 2)
show_image(enlarged_rocket_image, '3x Enlarged Rocket')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '7_rocket_enlarged.png'))
plt.close()
print("Resultado salvo em 'resultados/7_rocket_enlarged.png'\n")


"""### Proportionally resizing
We want to downscale the images of a veterinary blog website proportionally.
"""
print("--- 8. Redimensionamento Proporcional (Dogs) ---")
dogs_banner = plt.imread(get_image_path('dogs_banner.jpg'))

# Set proportional height so its half its size
height = int(dogs_banner.shape[0] / 2)
width = int(dogs_banner.shape[1] / 2)

# Resize using the calculated proportional height and width
image_resized = resize(dogs_banner, (height, width), anti_aliasing=True)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(dogs_banner, 'Original')
plt.subplot(1, 2, 2)
show_image(image_resized, 'Resized image')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '8_dogs_banner_resized.png'))
plt.close()
print("Resultado salvo em 'resultados/8_dogs_banner_resized.png'\n")


# =====================================================================
# Morphology
# =====================================================================

"""### Handwritten letters
Apply the morphological operation (erosion) that will discard the pixels near the letter boundaries.
"""
print("--- 9. Morfologia: Erosão (Letra R) ---")
upper_r_image_raw = plt.imread(get_image_path('r5.png'))

# Ensure correct conversion to gray and then binary
if upper_r_image_raw.ndim == 3:
    if upper_r_image_raw.shape[2] == 4:
        upper_r_image_raw = color.rgba2rgb(upper_r_image_raw)
    upper_r_image_gray = color.rgb2gray(upper_r_image_raw)
else:
    upper_r_image_gray = upper_r_image_raw

upper_r_image_bin = upper_r_image_gray > 0.5

# Obtain the eroded shape
eroded_image_shape = morphology.erosion(upper_r_image_bin)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(upper_r_image_bin, 'Original (Binary)')
plt.subplot(1, 2, 2)
show_image(eroded_image_shape, 'Eroded image')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '9_r5_eroded.png'))
plt.close()
print("Resultado salvo em 'resultados/9_r5_eroded.png'\n")


"""### Improving thresholded image
In this exercise, we'll try to reduce the noise of a thresholded image using the dilation morphological operation.
"""
print("--- 10. Morfologia: Dilatação (Mapa Mundi) ---")
world_image_raw = plt.imread(get_image_path('world_image_binary.jpg'))

# Ensure correct conversion to gray and then binary
if world_image_raw.ndim == 3:
    if world_image_raw.shape[2] == 4:
        world_image_raw = color.rgba2rgb(world_image_raw)
    world_image_gray = color.rgb2gray(world_image_raw)
else:
    world_image_gray = world_image_raw

world_image_bin = world_image_gray > 0.5

# Obtain the dilated image
dilated_image = morphology.dilation(world_image_bin)

# Plot and save comparison
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
show_image(world_image_bin, 'Original (Binary)')
plt.subplot(1, 2, 2)
show_image(dilated_image, 'Dilated image')
plt.tight_layout()
plt.savefig(os.path.join(resultados_dir, '10_world_dilated.png'))
plt.close()
print("Resultado salvo em 'resultados/10_world_dilated.png'\n")

print("Processamento concluído com sucesso!")