# -*- coding: utf-8 -*-
"""face_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lc4hcF3wKi1lnRoywu59zlOT_wYB9XrB
"""

import imutils  # redimencionamento, rotacao
import numpy as np
import cv2  # import OpenCV
import urllib.request
import os


def take_photo(filename='photo.jpg'):
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("[ERRO] Nao foi possivel abrir a webcam.")
        return None

    print("[INFO] Webcam aberta. Pressione ESPACO para capturar a foto ou ESC para cancelar.")
    while True:
        ret, frame = cap.read()
        if not ret:
            print("[ERRO] Nao foi possivel ler o frame da webcam.")
            break

        cv2.imshow("Pressione ESPACO para capturar", frame)
        key = cv2.waitKey(1) & 0xFF

        if key == 32:  # ESPAÇO
            is_success, im_buf_arr = cv2.imencode(".jpg", frame)
            if is_success:
                im_buf_arr.tofile(filename)
                print(f"[INFO] Foto salva como {filename}")
            else:
                print("[ERRO] Nao foi possivel codificar e salvar a foto.")
            break
        elif key == 27:  # ESC
            filename = None
            print("[INFO] Captura de foto cancelada pelo usuario.")
            break

    cap.release()
    cv2.destroyAllWindows()
    return filename


script_dir = os.path.dirname(os.path.abspath(__file__))
imagens_dir = os.path.join(script_dir, 'imagens')
resultados_dir = os.path.join(script_dir, 'resultados')

# Cria as pastas caso nao existam
os.makedirs(imagens_dir, exist_ok=True)
os.makedirs(resultados_dir, exist_ok=True)

photo_path = os.path.join(imagens_dir, 'photo.jpg')

image_file = take_photo(photo_path)
if image_file is None:
    print("[INFO] Nenhuma imagem capturada. Encerrando o script.")
    exit()

image = cv2.imdecode(np.fromfile(image_file, dtype=np.uint8), cv2.IMREAD_COLOR)
if image is None:
    print(f"[ERRO] Nao foi possivel ler a imagem de: {image_file}")
    exit()

# redimenciona para ter largura máxima de 400px
image = imutils.resize(image, width=400)
(h, w) = image.shape[:2]
print(w, h)
cv2.imshow("Imagem Original", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

prototxt_url = 'https://raw.githubusercontent.com/opencv/opencv/master/samples/dnn/face_detector/deploy.prototxt'
model_url = 'https://raw.githubusercontent.com/opencv/opencv_3rdparty/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel'

modelo_dir = os.path.join(script_dir, 'modelo')
os.makedirs(modelo_dir, exist_ok=True)

prototxt = os.path.join(modelo_dir, 'deploy.prototxt')
model = os.path.join(modelo_dir, 'res10_300x300_ssd_iter_140000.caffemodel')

if not os.path.exists(prototxt):
    print(f"[INFO] Baixando {prototxt}...")
    urllib.request.urlretrieve(prototxt_url, prototxt)

if not os.path.exists(model):
    print(f"[INFO] Baixando {model}...")
    urllib.request.urlretrieve(model_url, model)

print("Current working directory:", os.getcwd())
print("Script directory:", script_dir)
print("Files in script directory:", os.listdir(script_dir))

print("[INFO] carregando modelo...")
with open(prototxt, 'rb') as f:
    proto_arr = np.frombuffer(f.read(), dtype=np.uint8)
with open(model, 'rb') as f:
    model_arr = np.frombuffer(f.read(), dtype=np.uint8)
net = cv2.dnn.readNetFromCaffe(proto_arr, model_arr)
print("[INFO] Modelo carregado com sucesso!")

# redimensiona para ter uma largura máxima de 400 pixels
image = imutils.resize(image, width=400)
blob = cv2.dnn.blobFromImage(cv2.resize(
    image, (300, 300)), 1.0, (300, 300), (104.0, 177.0, 123.0))

print("[INFO] computing object detections ... ")
net.setInput(blob)
detections = net.forward()

for i in range(0, detections.shape[2]):
    # extrair a probabilidade associada a previsao
    confidence = detections[0, 0, i, 2]

    # filtra detecções fracas garantindo que a "confiança" seja maior que o limite minimo de confiança
    if confidence > 0.5:  # nossa detecção deve ter no minimo 50% de certeza
        # calcula as coordenadas (x, y) da caixa delimitadora do objeto
        box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
        (startX, startY, endX, endY) = box.astype("int")
        # desenha a caixa delimitadora da face junto com a probabilidade associada
        text = "{:.2f}".format(confidence * 100)
        y = startY - 10 if startY - 10 > 10 else startY + 10
        cv2.rectangle(image, (startX, startY), (endX, endY), (0, 0, 255), 2)
        cv2.putText(image, text, (startX, y),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 0, 255), 2)

cv2.imshow("Deteccao de Faces", image)
resultado_path = os.path.join(resultados_dir, 'photo_resultado.jpg')
is_success, im_buf_arr = cv2.imencode(".jpg", image)
if is_success:
    im_buf_arr.tofile(resultado_path)
    print(f"[INFO] Resultado salvo como {resultado_path}")
else:
    print("[ERRO] Nao foi possivel salvar o resultado.")
cv2.waitKey(0)
cv2.destroyAllWindows()
